# Generated by Django 5.1.1 on 2024-09-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=50, verbose_name='Продукт')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Введите цену продукта', max_digits=12, verbose_name='Цена')),
            ],
        ),
    ]
