# Generated by Django 5.1.1 on 2024-09-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену продукта', max_digits=12, verbose_name='Цена'),
        ),
    ]
