# Generated by Django 5.1.1 on 2024-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание продукта', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название продукта', max_length=50, null=True, verbose_name='Продукт'),
        ),
    ]
